import { ToastContainer } from 'react-toastify';
import { Header } from './components/Header'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

// const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="bg-blue-100">
        <ToastContainer/>
        <Header/>
        {children}
      </body>
    </html>
  )
}
